# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef4ba41273b960f03842e4d3f84aee16b2965d8c07d2d75663bda295784032a54ef0e921d1d9a07bf4c30ddec6782cb06448aa1f94fb9dfe0b3afa2b23891147

test:
  secret_key_base: 4f55c815e08a3987603ae207dfa385e35149bd56d66b25a70cee41a1e412665069a0c34cd073683f1141ace006f5b2851e3feab144c7192679a7473a564da62a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
